enableGlobalCache: true

nodeLinker: pnp

packageExtensions:
  "@angular/build@*":
    dependencies:
      tslib: "*"
  "@builder.io/qwik@*":
    dependencies:
      ignore: "*"
      semver: "*"
  "@nuxt/cli@*":
    dependencies:
      "@nuxt/kit": "*"
  "@nuxt/kit@*":
    dependencies:
      "@nuxt/schema": "*"
  "@remix-run/dev@*":
    dependencies:
      isbot: "*"
  "@vue/compiler-core@*":
    dependencies:
      "@babel/types": "*"
  vite-imagetools@*:
    peerDependencies:
      vite: "*"
  "@nuxt/schema@*":
    dependencies:
      "scule": "*"
  "unplugin-vue-router@*":
    dependencies:
      "@vue/compiler-sfc": "*"
